### ISSUE TITLE
Change "Profiles" font color to black

### ISSUE THREAD

**Issue by astridu** [sul-dlss/libapps#12]
On this page, the "PROFILES" text does not have sufficient contrast to its background. Please change the color to black.
https://guides.library.stanford.edu/prf.php
<img width="972" alt="image" src="https://github.com/user-attachments/assets/48921b77-5969-4a2b-8963-f6d3050b9355">

**Comment by corylown** [comment]
This style is coming from a css file hosted by Springshare but I think we can override it by setting `#s-lg-profile-count-btn { color: #000; }` in our locally managed styles in https://github.com/sul-dlss/libapps/blob/main/libguides/head.html
